version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
