name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build_and_push:
    name: build image using Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: 'False'
          
      - name: docker login 
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        
      - name: docker build
        run: docker build . -t our_py_img:${{ github.sha }}_${{ github.run_attempt }}

      - name: docker tag
        run: docker tag our_py_img:${{ github.sha }}_${{ github.run_attempt }} ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}
        
      - name: docker push
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}

  # push:
  #   needs: build
  #   name: push docker image to dockerhub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: docker tag
  #       run: docker tag our_py_img:${{ github.sha }}_${{ github.run_attempt }} ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}
  #     - name: docker push
  #       run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}
