name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    name: build image using Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: docker login 
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        
      - name: docker build
        run: docker build . -t ${{ secrets.DOCKER_USER }}/our_py_img_${{ github.run_attempt }}

  push:
    needs: build
    name: push docker image to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: docker push
        run: docker push ${{ secrets.DOCKER_USER }}/our_py_img_${{ github.run_attempt }}
